eureka:
  client:
    enabled: true
    fetch-registry: true
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/
  instance:
     preferIpAddress: true

management:
  endpoints:
     web:
      exposure:
         include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
    level:
        org:
            springframework: DEBUG
#server:
#  netty:
#    connection-timeout: 5
spring:
    application:
      name: feliz-people
    r2dbc:
#        password: admin
        password: mysecretpassword
#        url: r2dbc:postgres://localhost:5433/feliz_people
        url: r2dbc:postgres://localhost:5432/feliz_people
        username: postgres
        pool:
         enabled: true
         max-acquire-time: 5s  
    security:
     oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:9080/auth/realms/demo
        registration:
          oidc:
            client-id: webappy
            client-secret: 939b9997-21c7-4798-aa11-34534c57367b
